### ISSUE TITLE
Possible solution to ! trigger not enabling the popup

### ISSUE THREAD

**Issue by ksdavidc** [cwfryer/obsidian-callout-suggestions#6] opened 2024-06-18 01:42 UTC
Was getting the same issue as given here: https://github.com/cwfryer/obsidian-callout-suggestions/issues/3#issue-2279644589
where hte >! trigger was not triggering the popup.

I was checking for a possible plugin conflict, since the sandbox with just callout manager and suggester seemed to work.

I used divide and conquer plugin, and repeatedly went down a level until eventually the trigger worked. Then I worked my way back up all the way and this seems to have fixed it. Not sure why it fixed it, since I have all the same plugins installed, but now it works, even after restart.

**Comment by lnschroeder** [comment] 2024-07-28 14:30
In my case there seems to be a conflict with [Advanced Slides Plugin](https://github.com/MSzturc/obsidian-advanced-slides).
It seems that the order in which the plugins get enabled play a role. If _Advanced Slides_ is enabled before _Obsidian Callout Suggestion_ the suggestions won't appear.

I could fix this with the following steps `Settings -> Community plugins -> Installed plugins`:
1. enable _Callout Suggestion_ & disable _Advanced Slides_
2. click the _reload Plugins_ button
3. enable _Advanced Slides_ again
4. click the _reload Plugins_ button again

**Comment by cwfryer** [comment] 2024-07-29 15:55
> In my case there seems to be a conflict with [Advanced Slides Plugin](https://github.com/MSzturc/obsidian-advanced-slides). It seems that the order in which the plugins get enabled play a role. If _Advanced Slides_ is enabled before _Obsidian Callout Suggestion_ the suggestions won't appear.
> 
> I could fix this with the following steps `Settings -> Community plugins -> Installed plugins`:
> 
> 1. enable _Callout Suggestion_ & disable _Advanced Slides_
> 
> 2. click the _reload Plugins_ button
> 
> 3. enable _Advanced Slides_ again
> 
> 4. click the _reload Plugins_ button again

I just tested this on a fresh install and had the exact same issue as you describe. At least I can finally reproduce the issue!

Seems that the problem is with the [autosuggest](https://github.com/MSzturc/obsidian-advanced-slides/blob/main/src/suggesters/AutoCompleteSuggester.ts) feature from advanced slides.

By default, their suggest modal is active, and it doesn't have any trigger characters. It just triggers constantly on every input all the time. So I suppose any other suggest modals loaded after it are getting clobbered. Natural Language Dates doesn't even work under those same conditions.

@ksdavidc do you use Advanced Slides?

**Comment by ksdavidc** [comment] 2024-07-29 20:51
yes both advanced slides (which has since been forked to [Slides Extended](https://github.com/ebullient/obsidian-slides-extended) and Natural language dates. A bit busy right now or I would try to do some triage, but you are on the right track. You should probably check if the problem persists in the new version of the Slides, but it seems to be working for me as I have it now.

**Comment by cwfryer** [comment] 2024-07-29 22:39
At this point I'm confident the issue is caused by advanced-slides (and slides-extended).
I added steps to fix to the readme, and I'm going to close the issue.

**Closed as completed by cwfryer** 2024-07-29 22:39 UTC
